spring.application.name=resumenVentas

spring.datasource.url=jdbc:postgresql://localhost:5433/resumen_ventas
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

server.port=8080

external.gestion-recintos.base-url=http://localhost:8081

spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=always

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# Module1 external integration
external.module1.base-url=https://uncoated-unfixed-imaginary.ngrok-free.dev
external.module1.connect-timeout-ms=2000
external.module1.read-timeout-ms=5000
external.module1.enabled=true
external.module1.fallback-to-jpa=false
external.module1.ngrok-skip-browser-warning=true
# Map local evento id (seed DB) -> Module1 UUID
external.module1.mapping.1=b7fd05e3-1087-4b6d-818d-96a1a38e0e5b


